//User Register Constants
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

//User Login Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

//User Details Constants
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAILED = 'USER_DETAILS_FAILED'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

//User Details Constants
export const FRIEND_DETAILS_REQUEST = 'FRIEND_DETAILS_REQUEST'
export const FRIEND_DETAILS_SUCCESS = 'FRIEND_DETAILS_SUCCESS'
export const FRIEND_DETAILS_FAILED = 'FRIEND_DETAILS_FAILED'
export const FRIEND_DETAILS_RESET = 'FRIEND_DETAILS_RESET'

//User Update Profile Constants
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

//Get Conversation Constants
export const CONVERSATION_LIST_REQUEST = 'CONVERSATION_LIST_REQUEST'
export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS'
export const CONVERSATION_LIST_FAILED = 'CONVERSATION_LIST_FAILED'

//Create New Conversation Constants
export const CONVERSATION_CREATE_REQUEST = 'CONVERSATION_CREATE_REQUEST'
export const CONVERSATION_CREATE_SUCCESS = 'CONVERSATION_CREATE_SUCCESS'
export const CONVERSATION_CREATE_FAILED = 'CONVERSATION_CREATE_FAILED'
export const CONVERSATION_CREATE_RESET = 'CONVERSATION_CREATE_RESET'

//Delete Conversation Constants
export const CONVERSATION_DELETE_REQUEST = 'CONVERSATION_DELETE_REQUEST'
export const CONVERSATION_DELETE_SUCCESS = 'CONVERSATION_DELETE_SUCCESS'
export const CONVERSATION_DELETE_FAILED = 'CONVERSATION_DELETE_FAILED'

export const CURRENT_CHAT = 'CURRENT_CHAT'
export const CLEAR_CURRENT_CHAT = 'CLEAR_CURRENT_CHAT'

//Get Messages in a Conversation Details Constants
export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST'
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS'
export const MESSAGE_LIST_FAILED = 'MESSAGE_LIST_FAILED'

//Get Messages in a Conversation Details Constants
export const MESSAGE_LIST_CLEAR_REQUEST = 'MESSAGE_LIST_CLEAR_REQUEST'
export const MESSAGE_LIST_CLEAR_SUCCESS = 'MESSAGE_LIST_CLEAR_SUCCESS'
export const MESSAGE_LIST_CLEAR_FAILED = 'MESSAGE_LIST_CLEAR_FAILED'

//Create New Message Constants
export const MESSAGE_CREATE_REQUEST = 'MESSAGE_CREATE_REQUEST'
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS'
export const MESSAGE_CREATE_FAILED = 'MESSAGE_CREATE_FAILED'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const CLEAR_SENT_MESSAGE = 'CLEAR_SENT_MESSAGE'

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const CLEAR_RECEIVED_MESSAGE = 'CLEAR_RECEIVED_MESSAGE'

//Get Friends List Constants
export const FRIENDS_LIST_REQUEST = 'FRIENDS_LIST_REQUEST'
export const FRIENDS_LIST_SUCCESS = 'FRIENDS_LIST_SUCCESS'
export const FRIENDS_LIST_FAILED = 'FRIENDS_LIST_FAILED'

//Get Friend Requests List Constants
export const FRIEND_REQUESTS_LIST_REQUEST = 'FRIEND_REQUESTS_LIST_REQUEST'
export const FRIEND_REQUESTS_LIST_SUCCESS = 'FRIEND_REQUESTS_LIST_SUCCESS'
export const FRIEND_REQUESTS_LIST_FAILED = 'FRIEND_REQUESTS_LIST_FAILED'

//Get Sent Requests List Constants
export const SENT_REQUESTS_LIST_REQUEST = 'SENT_REQUESTS_LIST_REQUEST'
export const SENT_REQUESTS_LIST_SUCCESS = 'SENT_REQUESTS_LIST_SUCCESS'
export const SENT_REQUESTS_LIST_FAILED = 'SENT_REQUESTS_LIST_FAILED'

//Get Suggestions List Constants
export const SUGGESTIONS_LIST_REQUEST = 'SUGGESTIONS_LIST_REQUEST'
export const SUGGESTIONS_LIST_SUCCESS = 'SUGGESTIONS_LIST_SUCCESS'
export const SUGGESTIONS_LIST_FAILED = 'SUGGESTIONS_LIST_FAILED'

//Send Friend Request Constants
export const SEND_FRIEND_REQUEST_REQUEST = 'SEND_FRIEND_REQUEST_REQUEST'
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS'
export const SEND_FRIEND_REQUEST_FAILED = 'SEND_FRIEND_REQUEST_FAILED'

//Accept Friend Request Constants
export const ACCEPT_FRIEND_REQUEST_REQUEST = 'ACCEPT_FRIEND_REQUEST_REQUEST'
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS'
export const ACCEPT_FRIEND_REQUEST_FAILED = 'ACCEPT_FRIEND_REQUEST_FAILED'

//Delete Friend Request Constants
export const DELETE_FRIEND_REQUEST_REQUEST = 'DELETE_FRIEND_REQUEST_REQUEST'
export const DELETE_FRIEND_REQUEST_SUCCESS = 'DELETE_FRIEND_REQUEST_SUCCESS'
export const DELETE_FRIEND_REQUEST_FAILED = 'DELETE_FRIEND_REQUEST_FAILED'

//Delete Sent Request Constants
export const DELETE_SENT_REQUEST_REQUEST = 'DELETE_SENT_REQUEST_REQUEST'
export const DELETE_SENT_REQUEST_SUCCESS = 'DELETE_SENT_REQUEST_SUCCESS'
export const DELETE_SENT_REQUEST_FAILED = 'DELETE_SENT_REQUEST_FAILED'

//Unfriend Constants
export const UNFRIEND_REQUEST = 'UNFRIEND_REQUEST'
export const UNFRIEND_SUCCESS = 'UNFRIEND_SUCCESS'
export const UNFRIEND_FAILED = 'UNFRIEND_FAILED'
